# Generated by Django 5.2.4 on 2025-07-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('country_of_operation', models.CharField(max_length=100)),
                ('daily_sales_average', models.CharField(max_length=100)),
                ('monthly_ads_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method_issue', models.BooleanField(default=False)),
                ('ad_account_issue', models.BooleanField(default=False)),
                ('number_of_products', models.IntegerField()),
                ('product_type', models.CharField(max_length=255)),
                ('reason_for_contact', models.TextField()),
            ],
        ),
    ]
